repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=1000"]
  - repo: https://github.com/cpplint/cpplint
    rev: 2.0.2
    hooks:
      - id: cpplint
        args: ["--filter=-legal/copyright,-whitespace/line_length,-whitespace/parens"]
